In [1]:
import gc
import pandas as pd
import numpy as np
import seaborn as sns
import unicodedata
from datetime import datetime
from mapeamento_regioes_pb import mapear_regiao

In [2]:
"""def ler_filtrado(arquivo):
    chunks = []
    for chunk in pd.read_csv(arquivo, chunksize=50000, sep=';', encoding='latin1'):
        chunks.append(chunk[chunk['SG_UF'] == 'PB'])
        gc.collect()
    return pd.concat(chunks, ignore_index=True)

dfs = []

for ano in range(19, 24):
    arquivo = f'data/EstadoNutricional20{ano:02d}.csv'
    df_temp = ler_filtrado(arquivo)
    dfs.append(df_temp)
    del df_temp
    gc.collect()
    print(f"{arquivo} OK — {len(dfs[-1])} linhas")

df = pd.concat(dfs, ignore_index = True)"""

'def ler_filtrado(arquivo):\n    chunks = []\n    for chunk in pd.read_csv(arquivo, chunksize=50000, sep=\';\', encoding=\'latin1\'):\n        chunks.append(chunk[chunk[\'SG_UF\'] == \'PB\'])\n        gc.collect()\n    return pd.concat(chunks, ignore_index=True)\n\ndfs = []\n\nfor ano in range(19, 24):\n    arquivo = f\'data/EstadoNutricional20{ano:02d}.csv\'\n    df_temp = ler_filtrado(arquivo)\n    dfs.append(df_temp)\n    del df_temp\n    gc.collect()\n    print(f"{arquivo} OK — {len(dfs[-1])} linhas")\n\ndf = pd.concat(dfs, ignore_index = True)'

In [3]:
# df.to_csv('data/estado_nutricional_paraiba_2019-2023.csv', index = False)

In [2]:
df = pd.read_csv('data/estado_nutricional_paraiba_2019-2023.csv')

/tmp/ipykernel_106037/1138975021.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/estado_nutricional_paraiba_2019-2023.csv')

In [3]:
df.info()
df.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4245590 entries, 0 to 4245589
Data columns (total 34 columns):
 #   Column                       Dtype
---  ------                       -----
 0   CO_ACOMPANHAMENTO            object
 1   CO_PESSOA_SISVAN             object
 2   ST_PARTICIPA_ANDI            float64
 3   CO_MUNICIPIO_IBGE            int64
 4   SG_UF                        object
 5   NO_MUNICIPIO                 object
 6   CO_CNES                      float64
 7   NU_IDADE_ANO                 int64
 8   NU_FASE_VIDA                 object
 9   DS_FASE_VIDA                 object
 10  SG_SEXO                      object
 11  CO_RACA_COR                  int64
 12  DS_RACA_COR                  object
 13  CO_POVO_COMUNIDADE           float64
 14  DS_POVO_COMUNIDADE           object
 15  CO_ESCOLARIDADE              float64
 16  DS_ESCOLARIDADE              object
 17  DT_ACOMPANHAMENTO            object
 18  NU_COMPETENCIA               int64
 19  NU_PESO                      object
 20  NU_ALTURA                    object
 21  DS_IMC                       object
 22  DS_IMC_PRE_GESTACIONAL       float64
 23  PESO X IDADE                 object
 24  PESO X ALTURA                object
 25  CRI. ALTURA X IDADE          object
 26  CRI. IMC X IDADE             object
 27  ADO. ALTURA X IDADE          object
 28  ADO. IMC X IDADE             object
 29  CO_ESTADO_NUTRI_ADULTO       object
 30  CO_ESTADO_NUTRI_IDOSO        object
 31  CO_ESTADO_NUTRI_IMC_SEMGEST  object
 32  CO_SISTEMA_ORIGEM_ACOMP      int64
 33  SISTEMA_ORIGEM_ACOMP         object
dtypes: float64(5), int64(5), object(24)
memory usage: 1.1+ GB

,CO_ACOMPANHAMENTO,CO_PESSOA_SISVAN,ST_PARTICIPA_ANDI,CO_MUNICIPIO_IBGE,SG_UF,NO_MUNICIPIO,CO_CNES,NU_IDADE_ANO,NU_FASE_VIDA,DS_FASE_VIDA,...,PESO X ALTURA,CRI. ALTURA X IDADE,CRI. IMC X IDADE,ADO. ALTURA X IDADE,ADO. IMC X IDADE,CO_ESTADO_NUTRI_ADULTO,CO_ESTADO_NUTRI_IDOSO,CO_ESTADO_NUTRI_IMC_SEMGEST,CO_SISTEMA_ORIGEM_ACOMP,SISTEMA_ORIGEM_ACOMP
0,A3D749B0FFBAA35E12E568846831C5003880ECB7,27BADDBFFA4D5922EBB84DA9266CBDF680555404,NaN,251230,PB,PRINCESA ISABEL,2321661.0,5,"4,0",ENTRE 5 ANOS A 7 ANOS,...,NaN,Estatura adequada para a idade,Eutrofia,NaN,NaN,NaN,NaN,NaN,1,SISVAN WEB
1,F9EC83C6B8A32DFD32F05DB99D53B1CB88340A29,60C5C33457FD4F591CF656DCE2340CB985E9D819,NaN,250435,PB,CATURITE,7402430.0,51,"7,0",ADULTO,...,NaN,NaN,NaN,NaN,NaN,Obesidade Grau II,NaN,NaN,1,SISVAN WEB
2,434C6696FE2E704F764A4339BC7C3FCEC2222E17,34A0C399E89908F445CDFD96989E9A9662A1629B,NaN,251430,PB,SAO JOSE DE CAIANA,2604892.0,41,"7,0",ADULTO,...,NaN,NaN,NaN,NaN,NaN,Obesidade Grau I,NaN,Obesidade,1,SISVAN WEB
3,6857B2D0C64BB37849FC4EAB17FB302725B108AF,13A4A7112997C8ABA57EB7D49325C034105A2518,NaN,250040,PB,ALAGOA NOVA,3562247.0,3,"3,0",ENTRE 2 ANOS A 5 ANOS,...,Obesidade,Estatura adequada para a idade,Obesidade,NaN,NaN,NaN,NaN,NaN,4,E-SUS AB
4,9769F522A4144D8A600E5235937D42432FE1A103,8AFF953B8D34C41F276577361AE8BD197EC27391,NaN,250170,PB,BARRA DE SAO MIGUEL,2591871.0,14,"6,0",ADOLESCENTE,...,NaN,NaN,NaN,Estatura adequada para a idade,Eutrofia,NaN,NaN,NaN,4,E-SUS AB
5,409CCDE2DC4D0D70A266C5C48D0F97397C7C60F7,6BA0CCAA2446194ECAD69616EFC22861F6EA5B0D,NaN,251250,PB,QUEIMADAS,2357097.0,73,"8,0",IDOSO,...,NaN,NaN,NaN,NaN,NaN,NaN,Sobrepeso,NaN,4,E-SUS AB
6,48805342644E1500A1B31845024885ABEE9F4C70,34A63B11FD31C6F0B902ACBE9D5F677FD8829CB1,NaN,251500,PB,SAO MIGUEL DE TAIPU,2608928.0,8,"5,0",ENTRE 7 ANOS A 10 ANOS,...,NaN,Estatura adequada para a idade,Eutrofia,NaN,NaN,NaN,NaN,NaN,4,E-SUS AB
7,ABD7A9620EBB08B796E1DB8514D5144784FA3E77,D8CFC783BBC62EFE3013E2E30AF7D1C4AD9BBBD1,NaN,250390,PB,CAMALAU,2363321.0,45,"7,0",ADULTO,...,NaN,NaN,NaN,NaN,NaN,Sobrepeso,NaN,NaN,4,E-SUS AB
8,2F95053CE3B3CF0D9FF46CBAD104FAF2F73AFD22,52A33050A11E4A2DE8259B8FCF7953827D5B074B,NaN,251250,PB,QUEIMADAS,9667687.0,13,"6,0",ADOLESCENTE,...,NaN,NaN,NaN,Estatura adequada para a idade,Magreza,NaN,NaN,NaN,4,E-SUS AB
9,828A1167834ABB3277214656E79EB98BB36C38DE,5D379A6C91FBAB5AA959ECEB5060BAA8A993DD86,NaN,251597,PB,SOBRADO,3392422.0,34,"7,0",ADULTO,...,NaN,NaN,NaN,NaN,NaN,Sobrepeso,NaN,NaN,4,E-SUS AB

In [4]:
df.duplicated().sum()

np.int64(0)

In [6]:
# Altera os nomes das colunas para letras minúsculas para facilitar na utilização do código
#df.columns = df.columns.str.lower()

# Remoção de colunas de pouco valor preditivo

Algumas colunas possuem nenhum ou pouco valor preditivo, por exemplo, não queremos que a coluna sg_uf (UF que o caso foi notificado) tenha alguma tipo de influência no modelo, tendo em vista que o dataset utiliza apenas dados da Paraíba.

Outras colunas possuem informações administrativas do próprio sistema do SISVAN.

Todas as informações sobre as colunas estão descritas no dicionário de dados disponibilizado.

Checando coluna `st_participa_andi` que representa o status que indica se o município é participante do programa Atenção Nutricional à Desnutrição Infantil (ANDI).

In [5]:
nan_count = df['ST_PARTICIPA_ANDI'].isna().sum()
nan_count

np.int64(4245590)

Como todos os valores estão nulos vamos remover a coluna

In [6]:
df.drop(columns=['ST_PARTICIPA_ANDI'], axis=1, inplace=True, errors='ignore')

In [7]:
# Remoção de colunas sem valor preditivo
#df.drop(columns=['co_acompanhamento', 'co_pessoa_sisvan',
#                 'co_sistema_origem_acomp', 'sistema_origem_acomp'], axis=1, inplace=True, errors='ignore')

# ── 1. Remover colunas sem valor preditivo ─────────────────────────────────────
colunas_remover = [
    'CO_ACOMPANHAMENTO',     # ID interno, não generaliza
    'CO_PESSOA_SISVAN',      # ID interno do indivíduo
    'CO_CNES',               # ID do estabelecimento, muito granular
    'CO_MUNICIPIO_IBGE',     # código interno do IBGE, não é relevante
    'DS_RACA_COR',           # redundante com CO_RACA_COR (já é código)
    'DS_FASE_VIDA',          # redundante com NU_FASE_VIDA (já é código)
    'DS_ESCOLARIDADE',       # redundante com CO_ESCOLARIDADE (já é código)
    'DS_POVO_COMUNIDADE',    # redundante com CO_POVO_COMUNIDADE
    'DS_IMC',                # redundante com NU_PESO e NU_ALTURA
    'DS_IMC_PRE_GESTACIONAL',# não se aplica a adultos gerais
    'NU_COMPETENCIA',        # redundante com DT_ACOMPANHAMENTO
    'CO_SISTEMA_ORIGEM_ACOMP',
    'DS_SISTEMA_ORIGEM_ACOMP',
    'ST_PARTICIPA_ANDI',     # programa infantil, não relevante para adultos
]

df = df.drop(columns=[c for c in colunas_remover if c in df.columns], errors='ignore')

# ── 2. Manter apenas adultos (fase da vida = 7) ────────────────────────────────
df = df[df['NU_FASE_VIDA'] == 7].copy()

In [8]:
df.info()
df.head(10)

<class 'pandas.core.frame.DataFrame'>
Index: 925868 entries, 2179072 to 4245585
Data columns (total 21 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   SG_UF                        925868 non-null  object
 1   NO_MUNICIPIO                 925868 non-null  object
 2   NU_IDADE_ANO                 925868 non-null  int64
 3   NU_FASE_VIDA                 925868 non-null  object
 4   SG_SEXO                      925868 non-null  object
 5   CO_RACA_COR                  925868 non-null  int64
 6   CO_POVO_COMUNIDADE           632 non-null     float64
 7   CO_ESCOLARIDADE              422225 non-null  float64
 8   DT_ACOMPANHAMENTO            925868 non-null  object
 9   NU_PESO                      925868 non-null  object
 10  NU_ALTURA                    925868 non-null  object
 11  PESO X IDADE                 0 non-null       object
 12  PESO X ALTURA                0 non-null       object
 13  CRI. ALTURA X IDADE          0 non-null       object
 14  CRI. IMC X IDADE             0 non-null       object
 15  ADO. ALTURA X IDADE          0 non-null       object
 16  ADO. IMC X IDADE             0 non-null       object
 17  CO_ESTADO_NUTRI_ADULTO       915557 non-null  object
 18  CO_ESTADO_NUTRI_IDOSO        0 non-null       object
 19  CO_ESTADO_NUTRI_IMC_SEMGEST  28021 non-null   object
 20  SISTEMA_ORIGEM_ACOMP         925868 non-null  object
dtypes: float64(2), int64(2), object(17)
memory usage: 155.4+ MB

,SG_UF,NO_MUNICIPIO,NU_IDADE_ANO,NU_FASE_VIDA,SG_SEXO,CO_RACA_COR,CO_POVO_COMUNIDADE,CO_ESCOLARIDADE,DT_ACOMPANHAMENTO,NU_PESO,...,PESO X IDADE,PESO X ALTURA,CRI. ALTURA X IDADE,CRI. IMC X IDADE,ADO. ALTURA X IDADE,ADO. IMC X IDADE,CO_ESTADO_NUTRI_ADULTO,CO_ESTADO_NUTRI_IDOSO,CO_ESTADO_NUTRI_IMC_SEMGEST,SISTEMA_ORIGEM_ACOMP
2179072,PB,SOBRADO,37,7.0,F,4,NaN,99.0,03/01/2022,"127,75",...,NaN,NaN,NaN,NaN,NaN,NaN,Obesidade Grau III,NaN,NaN,AUXILIO BRASIL
2179073,PB,SAO JOSE DE PIRANHAS,36,7.0,F,1,NaN,4.0,11/01/2022,68,...,NaN,NaN,NaN,NaN,NaN,NaN,Adequado ou eutrófico,NaN,NaN,AUXILIO BRASIL
2179074,PB,SAO JOSE DE PIRANHAS,21,7.0,F,1,NaN,99.0,13/01/2022,54,...,NaN,NaN,NaN,NaN,NaN,NaN,Adequado ou eutrófico,NaN,NaN,AUXILIO BRASIL
2179076,PB,SAO JOSE DE PIRANHAS,55,7.0,F,99,NaN,99.0,03/01/2022,"74,8",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AUXILIO BRASIL
2179078,PB,REMIGIO,27,7.0,F,4,NaN,99.0,25/01/2022,63,...,NaN,NaN,NaN,NaN,NaN,NaN,Sobrepeso,NaN,NaN,AUXILIO BRASIL
2179079,PB,SOUSA,36,7.0,F,1,NaN,99.0,11/01/2022,70,...,NaN,NaN,NaN,NaN,NaN,NaN,Sobrepeso,NaN,NaN,AUXILIO BRASIL
2179080,PB,PRINCESA ISABEL,40,7.0,F,99,NaN,99.0,20/01/2022,"68,2",...,NaN,NaN,NaN,NaN,NaN,NaN,Sobrepeso,NaN,NaN,E-SUS AB
2179081,PB,SOLANEA,30,7.0,F,1,NaN,99.0,13/01/2022,74,...,NaN,NaN,NaN,NaN,NaN,NaN,Sobrepeso,NaN,NaN,AUXILIO BRASIL
2179082,PB,SOLEDADE,41,7.0,F,3,NaN,99.0,11/01/2022,"62,9",...,NaN,NaN,NaN,NaN,NaN,NaN,Sobrepeso,NaN,NaN,AUXILIO BRASIL
2179083,PB,SOSSEGO,23,7.0,F,3,NaN,99.0,03/01/2022,73,...,NaN,NaN,NaN,NaN,NaN,NaN,Obesidade Grau I,NaN,NaN,AUXILIO BRASIL

In [9]:
colunas_remover = [
    'SG_UF',                      # constante (todos PB)
    'PESO X IDADE',               # 0 non-null
    'PESO X ALTURA',              # 0 non-null
    'CRI. ALTURA X IDADE',        # 0 non-null
    'CRI. IMC X IDADE',           # 0 non-null
    'ADO. ALTURA X IDADE',        # 0 non-null
    'ADO. IMC X IDADE',           # 0 non-null
    'CO_ESTADO_NUTRI_IDOSO',      # 0 non-null
    'CO_ESTADO_NUTRI_IMC_SEMGEST',# subgrupo específico + mudança metodológica em 2022
    'CO_POVO_COMUNIDADE',         # 0.07% preenchido — ruído
]

df = df.drop(columns=colunas_remover)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 925868 entries, 2179072 to 4245585
Data columns (total 11 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   NO_MUNICIPIO            925868 non-null  object
 1   NU_IDADE_ANO            925868 non-null  int64
 2   NU_FASE_VIDA            925868 non-null  object
 3   SG_SEXO                 925868 non-null  object
 4   CO_RACA_COR             925868 non-null  int64
 5   CO_ESCOLARIDADE         422225 non-null  float64
 6   DT_ACOMPANHAMENTO       925868 non-null  object
 7   NU_PESO                 925868 non-null  object
 8   NU_ALTURA               925868 non-null  object
 9   CO_ESTADO_NUTRI_ADULTO  915557 non-null  object
 10  SISTEMA_ORIGEM_ACOMP    925868 non-null  object
dtypes: float64(1), int64(2), object(8)
memory usage: 84.8+ MB

In [11]:
# ── Ver distribuição da escolaridade ──────────────────────────────────────────
print("Distribuição CO_ESCOLARIDADE (incluindo nulos):")
print(df['CO_ESCOLARIDADE'].value_counts(dropna=False).sort_index())

print(f"\nNulos: {df['CO_ESCOLARIDADE'].isna().sum()} ({df['CO_ESCOLARIDADE'].isna().mean()*100:.1f}%)")
print(f"Preenchidos: {df['CO_ESCOLARIDADE'].notna().sum()} ({df['CO_ESCOLARIDADE'].notna().mean()*100:.1f}%)")

print(f"\nShape atual: {df.shape}")
print(df.dtypes)

Distribuição CO_ESCOLARIDADE (incluindo nulos):
CO_ESCOLARIDADE
1.0        815
2.0        889
3.0       2980
4.0       1165
5.0       1354
6.0       1218
7.0         44
8.0         43
9.0        110
10.0       791
11.0        44
12.0        35
13.0       156
14.0        11
15.0       305
99.0    412265
NaN     503643
Name: count, dtype: int64

Nulos: 503643 (54.4%)
Preenchidos: 422225 (45.6%)

Shape atual: (925868, 11)
NO_MUNICIPIO               object
NU_IDADE_ANO                int64
NU_FASE_VIDA               object
SG_SEXO                    object
CO_RACA_COR                 int64
CO_ESCOLARIDADE           float64
DT_ACOMPANHAMENTO          object
NU_PESO                    object
NU_ALTURA                  object
CO_ESTADO_NUTRI_ADULTO     object
SISTEMA_ORIGEM_ACOMP       object
dtype: object

In [12]:
# Escolaridade tem apenas 1.2% de dados reais — remover
df = df.drop(columns=['CO_ESCOLARIDADE'])

print(f"Shape atual: {df.shape}")
print(df.columns.tolist())

Shape atual: (925868, 10)
['NO_MUNICIPIO', 'NU_IDADE_ANO', 'NU_FASE_VIDA', 'SG_SEXO', 'CO_RACA_COR', 'DT_ACOMPANHAMENTO', 'NU_PESO', 'NU_ALTURA', 'CO_ESTADO_NUTRI_ADULTO', 'SISTEMA_ORIGEM_ACOMP']

In [13]:
print(df['CO_ESTADO_NUTRI_ADULTO'].value_counts(dropna=False).sort_index())

CO_ESTADO_NUTRI_ADULTO
Adequado ou eutrófico    279122
Baixo peso                19861
Obesidade Grau I         188637
Obesidade Grau II         69005
Obesidade Grau III        30344
Sobrepeso                328588
NaN                       10311
Name: count, dtype: int64

In [14]:
df = df.dropna(subset=['CO_ESTADO_NUTRI_ADULTO'])
print(f"Registros após remover nulos: {len(df)}")

# ── 2. Verificar NU_FASE_VIDA (deve estar constante após filtro de adultos) ───
print("\nDistribuição NU_FASE_VIDA:")
print(df['NU_FASE_VIDA'].value_counts(dropna=False))

Registros após remover nulos: 915557

Distribuição NU_FASE_VIDA:
NU_FASE_VIDA
7.0    915557
Name: count, dtype: int64

In [15]:
print("Amostras NU_PESO:", df['NU_PESO'].head(10).tolist())
print("Amostras NU_ALTURA:", df['NU_ALTURA'].head(10).tolist())
print("Amostras DT_ACOMPANHAMENTO:", df['DT_ACOMPANHAMENTO'].head(10).tolist())
print("Amostras SISTEMA_ORIGEM_ACOMP:", df['SISTEMA_ORIGEM_ACOMP'].unique())
print("Amostras NO_MUNICIPIO (únicos, primeiros 20):", 
      sorted(df['NO_MUNICIPIO'].unique())[:20])

Amostras NU_PESO: ['127,75', '68', '54', '63', '70', '68,2', '74', '62,9', '73', '79,8']
Amostras NU_ALTURA: ['153', '169', '156', '148', '158', '157', '163', '148', '145', '165']
Amostras DT_ACOMPANHAMENTO: ['03/01/2022', '11/01/2022', '13/01/2022', '25/01/2022', '11/01/2022', '20/01/2022', '13/01/2022', '11/01/2022', '03/01/2022', '20/01/2022']
Amostras SISTEMA_ORIGEM_ACOMP: ['AUXILIO BRASIL' 'E-SUS AB' 'SISVAN WEB']
Amostras NO_MUNICIPIO (únicos, primeiros 20): ['AGUA BRANCA', 'AGUIAR', 'ALAGOA GRANDE', 'ALAGOA NOVA', 'ALAGOINHA', 'ALCANTIL', 'ALGODAO DE JANDAIRA', 'ALHANDRA', 'AMPARO', 'APARECIDA', 'ARACAGI', 'ARARA', 'ARARUNA', 'AREIA', 'AREIA DE BARAUNAS', 'AREIAL', 'AROEIRAS', 'ASSUNCAO', 'BAIA DA TRAICAO', 'BANANEIRAS']

In [17]:
# ── 1. Carregar o CSV do Atlas Brasil e Dados do Índice de Gini ─────────────────────────────────────────
atlas = pd.read_csv('data/atlas_municipios_pb.csv', sep=';')
gini = pd.read_csv('data/ginipb.csv', sep=';', encoding='latin1', skiprows=2)

# ── 2. Selecionar apenas colunas relevantes ───────────────────────────────────
colunas_atlas = {
    'Territorialidades': 'municipio_key',
    'Renda per capita 2010': 'renda_per_capita',
    '% indivíduos pertencentes ao quinto mais pobre da distribuição dos indivíduos segundo a renda domiciliar per capita 2010': 'pct_quinto_mais_pobre',
    '% dos ocupados sem rendimento 2010': 'pct_sem_rendimento',
    '% dos ocupados com rendimento de até 1 salário mínimo 2010': 'pct_ate_1sm',
    'Razão 10% mais ricos / 40% mais pobres 2019': 'razao_desigualdade',
    'Produto Interno Bruto per capita 2013': 'pib_per_capita',
}

gini[["codigo", "municipio"]] = gini["Município"].str.split(" ", n=1, expand=True)
gini["2010"] = gini["2010"].str.replace(",", ".").astype(float)
gini_2010 = gini[["municipio", "2010"]]
gini_2010 = gini_2010.rename(columns={"municipio": "NO_MUNICIPIO", "2010": "GINI_2010"})

atlas = atlas[list(colunas_atlas.keys())].rename(columns=colunas_atlas)

# ── 3. Filtrar apenas municípios da PB e normalizar nome ──────────────────────
atlas = atlas[atlas['municipio_key'].str.contains('(PB)', regex=False, na=False)].copy()

def normalizar(texto):
    return unicodedata.normalize('NFKD', texto) \
        .encode('ASCII', 'ignore') \
        .decode('ASCII') \
        .upper() \
        .strip()

# Extrair nome limpo: "Água Branca (PB)" → "AGUA BRANCA"
atlas['NO_MUNICIPIO'] = atlas['municipio_key'] \
    .str.replace(r'\s*\(PB\)', '', regex=True) \
    .apply(normalizar)

# Normaliza municipios do dataframe gini_2010
gini_2010['NO_MUNICIPIO'] = gini_2010['NO_MUNICIPIO'].apply(normalizar)

# ── Corrigir nomes antigos → novos antes do merge ────────────────────────────
# Santarém (PB) foi renomeado para Joca Claudino em 2000
# Seridó (PB) foi renomeado para São Vicente do Seridó em 2008
atlas['NO_MUNICIPIO'] = atlas['NO_MUNICIPIO'].replace({
    'SANTAREM': 'JOCA CLAUDINO',
    'SERIDO':   'SAO VICENTE DO SERIDO',
})

atlas = atlas.drop(columns=['municipio_key'])

print(f"Atlas shape: {atlas.shape}")
print(f"Exemplo de chaves: {atlas['NO_MUNICIPIO'].head(5).tolist()}")

# ── 4. Verificar compatibilidade das chaves com o SISVAN ─────────────────────
municipios_sisvan = set(df['NO_MUNICIPIO'].unique())  # df = seu dataset SISVAN
municipios_atlas  = set(atlas['NO_MUNICIPIO'].unique())

apenas_sisvan = municipios_sisvan - municipios_atlas
apenas_atlas  = municipios_atlas  - municipios_sisvan

print(f"\nMunicípios no SISVAN mas não no Atlas: {sorted(apenas_sisvan)}")
print(f"Municípios no Atlas mas não no SISVAN: {sorted(apenas_atlas)}")

# ── Refazer o merge ───────────────────────────────────────────────────────────
df_merged = df.merge(atlas, on='NO_MUNICIPIO', how='left')
df_merged_final = df_merged.merge(gini_2010, on='NO_MUNICIPIO', how='left')

print(f"Shape após merge: {df_merged_final.shape}")
print(f"\nNulos nos indicadores econômicos:")
print(df_merged_final[['renda_per_capita','pct_quinto_mais_pobre',
                  'pct_sem_rendimento','pct_ate_1sm',
                  'razao_desigualdade','pib_per_capita', 'GINI_2010']].isnull().sum())

# ── Confirmar que não sobrou nenhum município sem match ───────────────────────
municipios_sem_match = df_merged_final[df_merged_final['renda_per_capita'].isnull()]['NO_MUNICIPIO'].unique()
print(f"\nMunicípios ainda sem match: {sorted(municipios_sem_match)}")

Atlas shape: (223, 7)
Exemplo de chaves: ['AGUA BRANCA', 'AGUIAR', 'ALAGOA GRANDE', 'ALAGOA NOVA', 'ALAGOINHA']

Municípios no SISVAN mas não no Atlas: []
Municípios no Atlas mas não no SISVAN: []
Shape após merge: (915557, 17)

Nulos nos indicadores econômicos:
renda_per_capita         0
pct_quinto_mais_pobre    0
pct_sem_rendimento       0
pct_ate_1sm              0
razao_desigualdade       0
pib_per_capita           0
GINI_2010                0
dtype: int64

Municípios ainda sem match: []

In [20]:
df = df_merged_final.copy()

In [21]:
df.head()

,NO_MUNICIPIO,NU_IDADE_ANO,NU_FASE_VIDA,SG_SEXO,CO_RACA_COR,DT_ACOMPANHAMENTO,NU_PESO,NU_ALTURA,CO_ESTADO_NUTRI_ADULTO,SISTEMA_ORIGEM_ACOMP,renda_per_capita,pct_quinto_mais_pobre,pct_sem_rendimento,pct_ate_1sm,razao_desigualdade,pib_per_capita,GINI_2010
0,SOBRADO,37,7.0,F,4,03/01/2022,"127,75",153,Obesidade Grau III,AUXILIO BRASIL,167.36,1.69,39.31,68.54,141.97,6.44,0.4921
1,SAO JOSE DE PIRANHAS,36,7.0,F,1,11/01/2022,68,169,Adequado ou eutrófico,AUXILIO BRASIL,188.04,2.33,16.43,56.70,161.99,5.70,0.5023
2,SAO JOSE DE PIRANHAS,21,7.0,F,1,13/01/2022,54,156,Adequado ou eutrófico,AUXILIO BRASIL,188.04,2.33,16.43,56.70,161.99,5.70,0.5023
3,REMIGIO,27,7.0,F,4,25/01/2022,63,148,Sobrepeso,AUXILIO BRASIL,300.86,2.31,30.85,63.98,184.13,5.69,0.5586
4,SOUSA,36,7.0,F,1,11/01/2022,70,158,Sobrepeso,AUXILIO BRASIL,322.80,3.12,5.62,42.03,289.34,9.96,0.5475

In [23]:
print(df.dtypes)
print(f"\nShape: {df.shape}")
print(f"\nColunas: {df.columns.tolist()}")

NO_MUNICIPIO               object
NU_IDADE_ANO                int64
NU_FASE_VIDA               object
SG_SEXO                    object
CO_RACA_COR                 int64
DT_ACOMPANHAMENTO          object
NU_PESO                    object
NU_ALTURA                  object
CO_ESTADO_NUTRI_ADULTO     object
SISTEMA_ORIGEM_ACOMP       object
renda_per_capita          float64
pct_quinto_mais_pobre     float64
pct_sem_rendimento        float64
pct_ate_1sm               float64
razao_desigualdade        float64
pib_per_capita            float64
GINI_2010                 float64
dtype: object

Shape: (915557, 17)

Colunas: ['NO_MUNICIPIO', 'NU_IDADE_ANO', 'NU_FASE_VIDA', 'SG_SEXO', 'CO_RACA_COR', 'DT_ACOMPANHAMENTO', 'NU_PESO', 'NU_ALTURA', 'CO_ESTADO_NUTRI_ADULTO', 'SISTEMA_ORIGEM_ACOMP', 'renda_per_capita', 'pct_quinto_mais_pobre', 'pct_sem_rendimento', 'pct_ate_1sm', 'razao_desigualdade', 'pib_per_capita', 'GINI_2010']

In [24]:
df_final = df.copy()

# ── 1. Remover colunas que não entram no modelo ───────────────────────────────
df_final = df_final.drop(columns=[
    'NU_PESO',             # Direção A: sem antropometria
    'NU_ALTURA',           # Direção A: sem antropometria
    'NU_FASE_VIDA',        # constante (todos adultos)
    'NO_MUNICIPIO',        # substituído pelos indicadores econômicos municipais
    'DT_ACOMPANHAMENTO',   # ANO_ACOMP removido — variação temporal fraca
])

# ── 2. Remover nulos do target ────────────────────────────────────────────────
df_final = df_final.dropna(subset=['CO_ESTADO_NUTRI_ADULTO'])

# ── 3. Encoding categóricas ───────────────────────────────────────────────────
df_final['SG_SEXO'] = df_final['SG_SEXO'].map({'M': 0, 'F': 1})

df_final['SISTEMA_ORIGEM_ACOMP'] = df_final['SISTEMA_ORIGEM_ACOMP'].map({
    'SISVAN WEB':    0,
    'AUXILIO BRASIL': 1,
    'E-SUS AB':       2,
})

# ── 4. Encoding do target ─────────────────────────────────────────────────────
target_map = {
    'Baixo peso':            0,
    'Adequado ou eutrófico': 1,
    'Sobrepeso':             2,
    'Obesidade Grau I':      3,
    'Obesidade Grau II':     4,
    'Obesidade Grau III':    5,
}
df_final['target'] = df_final['CO_ESTADO_NUTRI_ADULTO'].map(target_map)
df_final = df_final.drop(columns=['CO_ESTADO_NUTRI_ADULTO'])

# ── 5. Checar resultado ───────────────────────────────────────────────────────
print(f"Shape final: {df_final.shape}")
print(f"\nDtypes:\n{df_final.dtypes}")
print(f"\nNulos:\n{df_final.isnull().sum()}")
print(f"\nDistribuição do target:\n{df_final['target'].value_counts().sort_index()}")

Shape final: (915557, 12)

Dtypes:
NU_IDADE_ANO               int64
SG_SEXO                    int64
CO_RACA_COR                int64
SISTEMA_ORIGEM_ACOMP       int64
renda_per_capita         float64
pct_quinto_mais_pobre    float64
pct_sem_rendimento       float64
pct_ate_1sm              float64
razao_desigualdade       float64
pib_per_capita           float64
GINI_2010                float64
target                     int64
dtype: object

Nulos:
NU_IDADE_ANO             0
SG_SEXO                  0
CO_RACA_COR              0
SISTEMA_ORIGEM_ACOMP     0
renda_per_capita         0
pct_quinto_mais_pobre    0
pct_sem_rendimento       0
pct_ate_1sm              0
razao_desigualdade       0
pib_per_capita           0
GINI_2010                0
target                   0
dtype: int64

Distribuição do target:
target
0     19861
1    279122
2    328588
3    188637
4     69005
5     30344
Name: count, dtype: int64

nao_mapeados = df[df['regiao'] == 'Não identificado']['NO_MUNICIPIO'].unique()
print(f"Não mapeados ({len(nao_mapeados)}): {sorted(nao_mapeados)}")